root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
extends:
  - "plugin:vue/essential"
  # - 'plugin:@typescript-eslint/recommended'
  - "@vue/prettier"
  - "@vue/typescript"
  # - 'plugin:prettier/recommended'
  # - 'prettier/@typescript-eslint'
  # - 'prettier/vue'
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - 'error'
  no-console: 0
