root: true
env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
extends:
  - "plugin:vue/essential"
  - "@vue/prettier"
  - "@vue/typescript"
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - 'error'
  no-console: 0
