# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

gem "pg"
gem "puma", "~> 3.11"
gem "rails", "~> 5.2.3"

gem "devise"
gem 'devise_token_auth'
gem "omniauth"
gem "omniauth-google-oauth2"
gem "pundit"
gem "rack-cors"

gem "jbuilder", "~> 2.5"
gem "slim-rails"

# gem 'redis', '~> 4.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]

  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "shoulda-matchers"
  gem "rails-controller-testing"
  gem "simplecov", require: false

  gem "forgery_ja"
  gem "faker"

  gem "pry-rails"
  gem "pry-byebug"
  gem "pry-doc"
end

group :development do
  gem "better_errors"
  gem "brakeman", require: false
  gem "bullet"
  gem "letter_opener"
  gem "letter_opener_web"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "rack-mini-profiler", require: false
  gem "rails_best_practices"
  gem "rubocop", require: false
  gem "rubocop-performance"
  gem "rubocop-rails_config"
  gem "rubocop-rspec"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

group :test do
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "admin", path: "admin"
